### ISSUE TITLE
error witn .env example

### ISSUE THREAD

**Issue by mr-brune** [Denperidge/facebook-event-aggregator#6]
it gives me this error with python 3.10.8

`Traceback (most recent call last):
  File "/home/mrbrune/facebook-event-aggregator/app/main.py", line 42, in <module>
    pages = read_pages_from_env()
  File "/home/mrbrune/facebook-event-aggregator/app/scrape_and_parse/scrape_and_parse.py", line 143, in read_pages_from_env
    raw_pages = loads(getenv("pages"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 71 (char 70)`

**Comment by mr-brune** [comment]
ok solved in this pull #5

**Comment by Denperidge** [comment]
Wacky oversight on my end, thank you for spotting & fixing it!
